services:
  - type: web
    name: petbloom-api-thecla
    runtime: python
    rootDir: back-end
    buildCommand: pip install -r requirements.txt && prisma generate
    startCommand: prisma db push --accept-data-loss && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: petbloom-postgres-thecla
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_ALGORITHM
        value: HS256
      - key: FRONTEND_URL
        value: https://your-netlify-site.netlify.app

databases:
  - name: petbloom-postgres-thecla
    databaseName: petbloom
    user: petbloom
